// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxWlVdU4A1pWROdkBFM40vLyCUr5t7EWg',
    appId: '1:535150690951:web:0631ecefe664072ae82e22',
    messagingSenderId: '535150690951',
    projectId: 'to-do-d7c7b',
    authDomain: 'to-do-d7c7b.firebaseapp.com',
    storageBucket: 'to-do-d7c7b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTr7K7e0wHyipAve0-fQlBtSR4hN0rnyo',
    appId: '1:535150690951:android:6193ded5db34f92fe82e22',
    messagingSenderId: '535150690951',
    projectId: 'to-do-d7c7b',
    storageBucket: 'to-do-d7c7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClLXdG1HKwqM830h6KCA0qf_kTAe3HLk4',
    appId: '1:535150690951:ios:be8a7dc070c06f56e82e22',
    messagingSenderId: '535150690951',
    projectId: 'to-do-d7c7b',
    storageBucket: 'to-do-d7c7b.firebasestorage.app',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClLXdG1HKwqM830h6KCA0qf_kTAe3HLk4',
    appId: '1:535150690951:ios:be8a7dc070c06f56e82e22',
    messagingSenderId: '535150690951',
    projectId: 'to-do-d7c7b',
    storageBucket: 'to-do-d7c7b.firebasestorage.app',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxWlVdU4A1pWROdkBFM40vLyCUr5t7EWg',
    appId: '1:535150690951:web:425bbe6625d13635e82e22',
    messagingSenderId: '535150690951',
    projectId: 'to-do-d7c7b',
    authDomain: 'to-do-d7c7b.firebaseapp.com',
    storageBucket: 'to-do-d7c7b.firebasestorage.app',
  );
}
